# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:erbium-bullseye-browsers-legacy
    steps:
      - checkout
      - run: echo "hello world" > output.txt
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - output.txt

  print_output_file:
    docker:
      - image: circleci/node:erbium-bullseye-browsers-legacy
    steps:
      - checkout
      - attach_workspace:
          at: /home/circleci
      - run:
          name: 'print output file'
          command: |
            cat /home/circleci/output.txt

workflows:
  print-sharingFile-workflow:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
